include:
    - remote: "http://ftfdsvp245.fr.st.space.corp/astre/astre-components/-/raw/absplus-1.3/git/template_astre_runner.yml"

# Test jobs triggered only at branch push
test_debian10:
    extends: .test_debian10

# Deployment jobs triggered only at new tag push
deploy_debian10:
    extends: .deploy_debian10

deploy_raspberry:
    extends: .deploy_raspberry
